version: '3'
services: 
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    # networks:
    #   - django_web
  mysql:
    image: mysql:5.6
    volumes:
    - /var/lib/mysql
    ports:
      - 3306:3306
    # networks:
    #   - django_web
    env_file:
      - mysite/.env
    # environment:
    #   MYSQL_DATABASE: 'mydatabase'
    #   MYSQL_USER: 'root'
    #   MYSQL_ROOT_PASSWORD: ""
    #   MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

# networks:
#   django_web:
